### ISSUE TITLE
DOCKER  配置端口多少呀？数据库要配置吗？

### ISSUE THREAD

**Issue by oemsys** [getmoneynote/moneywhere-user-fe#1]
DOCKER  配置端口多少呀？数据库要配置吗？  安卓APP怎么搞呀？  安卓搞个配置可以配置自己的服务器地址端口  www.money.com:8888

**Comment by markliu2013** [comment]
请使用最新的docker compose项目部署。
https://github.com/getmoneynote/docker-compose-moneywhere
